# Generated by Django 5.0 on 2024-01-16 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_code",
                    models.TextField(
                        choices=[
                            ("Mon", "Monday"),
                            ("Tue", "Tuesday"),
                            ("Wed", "Wednesday"),
                            ("Thu", "Thursday"),
                            ("Fri", "Friday"),
                            ("Sat", "Saturday"),
                            ("Sun", "Sunday"),
                        ],
                        default="Mon",
                        max_length=3,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trainNumber", models.IntegerField(unique=True)),
                ("trainName", models.CharField(max_length=100)),
                ("departureTime", models.TimeField(null=True)),
                ("arrivalTime", models.TimeField(null=True)),
                ("daysOfJourney", models.PositiveIntegerField(null=True)),
                ("totalDistance", models.IntegerField()),
                ("numberOfSeats", models.PositiveIntegerField()),
                (
                    "baseFare",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "farePerKilometre",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("numberOfStops", models.IntegerField(default=0)),
                (
                    "daysOfWeek",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select the days of the week",
                        related_name="daysOfWeek",
                        to="trains.day",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destination",
                        to="stations.station",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source",
                        to="stations.station",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distance",
                    models.DecimalField(decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stations.station",
                    ),
                ),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="trains.train",
                    ),
                ),
            ],
            options={
                "ordering": ["distance"],
            },
        ),
        migrations.CreateModel(
            name="TrainRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure_date", models.DateField()),
                ("arrival_date", models.DateField()),
                ("numberOfAvailableSeats", models.IntegerField(default=12)),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="train_runs",
                        to="trains.train",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("daysRequiredToReach", models.PositiveIntegerField(default=0)),
                ("date", models.DateField(null=True)),
                ("arrivalTime", models.TimeField()),
                ("departureTime", models.TimeField()),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stations.station",
                    ),
                ),
                (
                    "trainRun",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="trains.trainrun",
                    ),
                ),
            ],
        ),
    ]
