# Generated by Django 5.0 on 2024-01-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trains", "0002_route_distance_train_daysofweek_trainrun"),
    ]

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_code",
                    models.TextField(
                        choices=[
                            ("Mon", "Monday"),
                            ("Tue", "Tuesday"),
                            ("Wed", "Wednesday"),
                            ("Thu", "Thursday"),
                            ("Fri", "Friday"),
                            ("Sat", "Saturday"),
                            ("Sun", "Sunday"),
                        ],
                        max_length=3,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="train",
            name="daysOfWeek",
        ),
        migrations.AddField(
            model_name="train",
            name="daysOfWeek",
            field=models.ManyToManyField(
                blank=True, help_text="Select the days of the week", to="trains.day"
            ),
        ),
    ]
