# Generated by Django 5.0 on 2024-01-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trains", "0002_seatclass_remove_train_basefare_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seatclass",
            name="seat_class",
            field=models.TextField(
                choices=[
                    ("3A", "ThirdAC"),
                    ("2A", "SecondAC"),
                    ("1A", "FirstAC"),
                    ("S", "Sleeper"),
                ],
                default="S",
            ),
        ),
    ]
