# Generated by Django 5.0 on 2024-01-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trains", "0003_day_remove_train_daysofweek_train_daysofweek"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainrun",
            name="numberOfAvailableSeats",
            field=models.IntegerField(default=12),
        ),
    ]
