# Generated by Django 5.0 on 2024-01-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trains", "0004_trainrun_numberofavailableseats"),
    ]

    operations = [
        migrations.AddField(
            model_name="train",
            name="fare",
            field=models.IntegerField(default=100),
        ),
    ]
