# Generated by Django 5.0 on 2024-01-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trains", "0005_train_fare"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainrun",
            name="fare",
            field=models.IntegerField(default=100),
        ),
    ]
