# Generated by Django 5.0 on 2024-01-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0001_initial"),
        ("trains", "0006_trainrun_fare"),
    ]

    operations = [
        migrations.AddField(
            model_name="train",
            name="route",
            field=models.ManyToManyField(
                blank=True, related_name="trains", to="stations.station"
            ),
        ),
    ]
