# Generated by Django 5.0 on 2024-01-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trains", "0008_alter_route_options_remove_train_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="train",
            name="totalDistance",
            field=models.IntegerField(null=True),
        ),
    ]
