# Generated by Django 5.0 on 2024-01-08 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trains", "0009_train_totaldistance"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="route",
            options={"ordering": ["distance"]},
        ),
        migrations.RemoveField(
            model_name="route",
            name="order",
        ),
    ]
