# Generated by Django 5.0 on 2024-01-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trains", "0010_alter_route_options_remove_route_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="day",
            field=models.TextField(
                choices=[
                    ("Mon", "Monday"),
                    ("Tue", "Tuesday"),
                    ("Wed", "Wednesday"),
                    ("Thu", "Thursday"),
                    ("Fri", "Friday"),
                    ("Sat", "Saturday"),
                    ("Sun", "Sunday"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="day_code",
            field=models.IntegerField(null=True),
        ),
    ]
