# Generated by Django 5.0 on 2024-01-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trains", "0011_day_day_alter_day_day_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="day",
            field=models.TextField(
                choices=[
                    ("Mon", "Monday"),
                    ("Tue", "Tuesday"),
                    ("Wed", "Wednesday"),
                    ("Thu", "Thursday"),
                    ("Fri", "Friday"),
                    ("Sat", "Saturday"),
                    ("Sun", "Sunday"),
                ],
                default="Sun",
                max_length=3,
            ),
        ),
    ]
