# Generated by Django 5.0 on 2024-01-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trains", "0013_train_daysofjourney"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="day",
            name="day",
        ),
        migrations.RemoveField(
            model_name="train",
            name="fare",
        ),
        migrations.RemoveField(
            model_name="trainrun",
            name="fare",
        ),
        migrations.AddField(
            model_name="train",
            name="arrivalTime",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="train",
            name="baseFare",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="train",
            name="departureTime",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="train",
            name="farePerKilometre",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="train",
            name="numberOfStops",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="day",
            name="day_code",
            field=models.TextField(
                choices=[
                    ("Mon", "Monday"),
                    ("Tue", "Tuesday"),
                    ("Wed", "Wednesday"),
                    ("Thu", "Thursday"),
                    ("Fri", "Friday"),
                    ("Sat", "Saturday"),
                    ("Sun", "Sunday"),
                ],
                default="Mon",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="train",
            name="daysOfJourney",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="train",
            name="totalDistance",
            field=models.IntegerField(),
        ),
    ]
