# Generated by Django 5.0 on 2024-01-13 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trains", "0014_remove_day_day_remove_train_fare_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="train",
        ),
        migrations.AddField(
            model_name="schedule",
            name="Date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="daysRequiredToReach",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="schedule",
            name="trainRun",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="trains.trainrun",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="arrivalTime",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="departureTime",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="train",
            name="daysOfJourney",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
