# Generated by Django 5.0 on 2024-01-13 22:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trains", "0015_remove_schedule_train_schedule_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="Date",
            new_name="date",
        ),
    ]
