# Generated by Django 5.0 on 2024-01-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trains", "0016_rename_date_schedule_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="train",
            name="farePerKilometre",
            field=models.FloatField(null=True),
        ),
    ]
