# Generated by Django 5.0 on 2024-01-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trains", "0017_alter_train_fareperkilometre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="train",
            name="baseFare",
            field=models.FloatField(null=True),
        ),
    ]
