# Generated by Django 5.0 on 2024-01-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trains", "0018_alter_train_basefare"),
    ]

    operations = [
        migrations.AlterField(
            model_name="train",
            name="baseFare",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="train",
            name="farePerKilometre",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
