# Generated by Django 5.0 on 2024-01-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_customer",
            field=models.BooleanField(default=False, verbose_name="is_customer"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="is_staff"),
        ),
    ]
