# Generated by Django 5.0 on 2024-01-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_is_customer_alter_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="money",
            field=models.IntegerField(default=0),
        ),
    ]
