# Generated by Django 5.0 on 2024-01-05 02:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_money"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="money",
        ),
    ]
