# Generated by Django 5.0 on 2024-01-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_user_money"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_customer",
            field=models.BooleanField(default=True, verbose_name="is_customer"),
        ),
    ]
