# Generated by Django 5.0 on 2024-01-05 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
        ("tickets", "0005_alter_passenger_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="tickets",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="tickets.ticket",
            ),
        ),
    ]
