# Generated by Django 5.0 on 2024-01-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_alter_profile_wallet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="wallet",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
