# Generated by Django 5.0 on 2024-01-02 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0001_initial"),
        ("trains", "0002_route_distance_train_daysofweek_trainrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="seatNumber",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="passenger",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="tickets.passenger"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="train",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="trains.trainrun"
            ),
        ),
    ]
