# Generated by Django 5.0 on 2024-01-05 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0002_ticket_seatnumber_ticket_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="passenger",
            name="ticket",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passengers",
                to="tickets.ticket",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="passenger",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="tickets.passenger",
            ),
        ),
    ]
