# Generated by Django 5.0 on 2024-01-16 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0002_initial"),
        ("trains", "0002_seatclass_remove_train_basefare_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="seatClass",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trains.seatclass",
            ),
        ),
    ]
