# Generated by Django 5.0 on 2024-01-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0003_ticket_seatclass"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="fare",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
