# Generated by Django 5.0 on 2024-01-05 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0003_passenger_ticket_ticket_date_alter_ticket_passenger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="passenger",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="tickets.passenger",
            ),
        ),
    ]
