# Generated by Django 5.0 on 2024-01-06 05:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0005_alter_passenger_ticket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="unique_id",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
