# Generated by Django 5.0 on 2024-01-06 11:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0006_remove_ticket_unique_id_alter_ticket_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
