# Generated by Django 5.0 on 2024-01-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0007_alter_ticket_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
