# Generated by Django 5.0 on 2024-01-14 00:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0013_alter_ticket_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="train",
            new_name="trainRun",
        ),
    ]
